# Generated by Django 5.2.4 on 2025-07-25 01:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=128)),
                ('cpf_cnpj', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'Produtores',
            },
        ),
        migrations.CreateModel(
            name='Safra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('ano', models.CharField(max_length=4, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=128)),
                ('cidade', models.CharField(max_length=64)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('DF', 'Distrito Federal')], max_length=2)),
                ('area_total_fazenda', models.DecimalField(decimal_places=1, max_digits=6)),
                ('area_agricultavel', models.DecimalField(decimal_places=1, max_digits=6)),
                ('area_vegetacao', models.DecimalField(decimal_places=1, max_digits=6)),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produtor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plantio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cultura')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.propriedade')),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.safra')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
