# Generated by Django 5.2.4 on 2025-07-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtor',
            options={'verbose_name_plural': 'Produtores'},
        ),
        migrations.AlterField(
            model_name='plantio',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
