# Generated by Django 5.2.4 on 2025-07-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_produtor_options_alter_plantio_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safra',
            name='ano',
            field=models.CharField(max_length=4),
        ),
    ]
