# Generated by Django 5.2.4 on 2025-07-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_propriedade_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultura',
            name='descricao',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='safra',
            name='ano',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
